# CS106A - Lecture 5 - More Images


# Loops
# - UBNI, Up to But Not including n
for x in range(10):
  ...
  ...
  ...
# - Nested loops are loops inside loops.
for y in range(image.height):
  for x in range(image.width):
    ...
    ...
    ...
# - Don't do these problems in your head, sketch them out!
